# module_8_2
"Сложные моменты и исключения в стеке вызовов функции"

Цель: разобраться в том, как работают исключения внутри функций и как их обрабатывать на практике с помощью try-except.

## Задача "План перехват"

Напишите две функции:

### Функция personal_sum(numbers)

Эта функция должна принимать коллекцию чисел и подсчитывать их сумму путем перебора, увеличивая переменную result. Если при переборе встречается значение, не являющееся числом, должно быть обработано исключение TypeError и счетчик incorrect_data увеличен на 1.

В итоге функция должна возвращать кортеж из двух значений: result — сумму чисел и incorrect_data — количество некорректных данных.

### Функция calculate_average(numbers)

Среднее арифметическое — это сумма всех данных, деленная на их количество.

Эта функция должна принимать коллекцию чисел и возвращать среднее арифметическое всех чисел. Для подсчета суммы она использует ранее написанную функцию personal_sum.

Поскольку коллекция чисел может оказаться пустой, при делении на 0 должно быть обработано исключение ZeroDivisionError, и функция должна вернуть 0. Также в numbers может быть записана не коллекция, а другие типы данных, например, числа. В таком случае необходимо обработать исключение TypeError, выводя строку 'В numbers записан некорректный тип данных'. В этом случае функция должна вернуть None.

## Пункты задачи

1. Создайте функцию personal_sum, следуя условиям задачи.
2. Создайте функцию calculate_average, также соблюдая все условия.
3. Вызовите функцию calculate_average несколько раз, передавая ей данные различных типов.

## Пример выполнения программы

Вот несколько примеров, иллюстрирующих работу функции calculate_average:

```python
print(f'Результат 1: {calculate_average("1, 2, 3")}')  # Строка перебирается, но каждый символ имеет строковый тип
print(f'Результат 2: {calculate_average([1, "Строка", 3, "Ещё Строка"])}')  # Учитываются только 1 и 3
print(f'Результат 3: {calculate_average(567)}')  # Передана не коллекция
print(f'Результат 4: {calculate_average([42, 15, 36, 13])}')  # Всё должно работать правильно
```

Вывод на консоль:

```
Некорректный тип данных для подсчёта суммы – 1
Некорректный тип данных для подсчёта суммы -,
Некорректный тип данных для подсчёта суммы -
Некорректный тип данных для подсчёта суммы – 2
Некорректный тип данных для подсчёта суммы -,
Некорректный тип данных для подсчёта суммы -
Некорректный тип данных для подсчёта суммы – 3
Результат 1: 0
Некорректный тип данных для подсчёта суммы – Строка
Некорректный тип данных для подсчёта суммы – Ещё Строка
Результат 2: 2.0
В numbers записан некорректный тип данных
Результат 3: None.
```
Результат 4: 26.5
